# -*- coding: utf-8 -*-
"""Contenu métier du classeur Registre des incidents et des escalades.

Listes de saisie, matrice de criticité, champs du registre et dictionnaire des
indicateurs. Les cibles sont des valeurs par défaut (standards de marché ITSM ou
hypothèses SGP non cotée) reprises dans l'onglet Données, où elles se modifient.
"""

FONDS_PROD = [
    "AirFund Conviction Value Capital",
    "Openstone Infraworld",
    "Aletheon Growth III S.L.P.",
    "Partners Group PEO Eltif Feeder",
    "Otentiq Private Equity X",
    "Fundcraft France SAS",
]
FONDS_DEMO = [
    "Fonds test 1 (FoF PE evergreen)",
    "Fonds test 2 (closed-end)",
    "Fonds test 3 (FPS infrastructure)",
    "Fonds test 4 (onboarding)",
    "Fonds test 5 (nourricier ELTIF)",
    "SGP test (transverse)",
]

TYPES = ["Incident", "Quasi-incident"]
STATUTS = ["Ouvert", "En cours", "En escalade", "Résolu", "Clos", "Annulé"]
OUINON = ["Oui", "Non"]

DOMAINES = [
    "Valorisation et VL",
    "Passif (souscriptions, rachats, registre)",
    "Appels de fonds et distributions",
    "Trésorerie et paiements",
    "Investissements et limites (ratios)",
    "Liquidité (gates, outils de gestion)",
    "Conformité et LCB-FT",
    "Reporting réglementaire (Annex IV, PRIIPs, EET)",
    "Reporting investisseurs",
    "Systèmes d'information et cybersécurité (TIC)",
    "Délégataires et prestataires",
    "Juridique et documentation des fonds",
    "Autre",
]

BALE = [
    "Fraude interne",
    "Fraude externe",
    "Pratiques en matière d'emploi et sécurité au travail",
    "Clients, produits et pratiques commerciales",
    "Dommages aux actifs physiques",
    "Interruption d'activité et dysfonctionnement des systèmes",
    "Exécution, livraison et gestion des processus",
]

# (libellé, détection interne)
SOURCES = [
    ("Contrôle de 1er niveau (opérationnel)", "Oui"),
    ("Contrôle de 2nd niveau (Risk / Conformité)", "Oui"),
    ("Alerte automatique (outil, rapprochement)", "Oui"),
    ("Délégataire ou prestataire (administrateur, TA)", "Oui"),
    ("Dépositaire", "Non"),
    ("Investisseur ou distributeur", "Non"),
    ("Commissaire aux comptes ou audit", "Non"),
    ("Régulateur (AMF)", "Non"),
]

# (libellé, prise en compte h ouvrées, résolution j.o., niveau requis, délai max d'escalade h ouvrées, critères)
CRITICITES = [
    ("1 - Critique", 1, 1, 3, 2,
     "Impact avéré sur les investisseurs ou la VL au-delà du seuil de significativité, manquement réglementaire, "
     "incident TIC majeur DORA, atteinte à la réputation ou perte au-delà du seuil d'appétence."),
    ("2 - Majeure", 2, 3, 2, 4,
     "Impact potentiel sur un fonds ou des investisseurs, dépassement de limite d'investissement, retard d'un "
     "reporting réglementaire ou d'un appel de fonds, perte significative mais sous le seuil d'appétence."),
    ("3 - Modérée", 9, 10, 1, None,
     "Erreur corrigée avant tout impact externe, retard opérationnel sans conséquence pour les investisseurs."),
    ("4 - Mineure", 18, 20, 1, None,
     "Anomalie de forme ou de documentation, sans impact financier, investisseur ni réglementaire."),
]

NIVEAUX = [
    ("N1", "Opérationnel", 1,
     "Équipe en charge : gestion, middle et back-office, administrateur, agent de transfert, prestataire. "
     "Traitement courant."),
    ("N2", "Contrôle", 2,
     "Risk Management et/ou RCCI saisis formellement pour qualification, arbitrage et suivi du plan d'action. "
     "La seule inscription au registre n'est pas une escalade."),
    ("N3", "Direction", 3,
     "Dirigeants effectifs ou Comité des risques : décision (indemnisation, suspension, communication)."),
    ("N4", "Externe", 4,
     "Notification à l'AMF (dont DORA), au dépositaire, aux investisseurs ou au commissaire aux comptes."),
]

# Champs saisis : clé, colonne, bloc, libellé, obligatoire, format, définition, exemple
CHAMPS = [
    ("ID", "B", "Identification", "ID incident", "Oui", "Texte",
     "Identifiant unique, une ligne par événement ; format conseillé INC-AAAA-NNN.", "INC-2026-014"),
    ("Type", "C", "Identification", "Type", "Oui", "Liste",
     "Incident (événement avéré) ou Quasi-incident (événement évité avant tout impact).", "Incident"),
    ("Fonds", "D", "Identification", "Fonds / véhicule", "Oui", "Liste",
     "Fonds ou véhicule concerné ; ligne transverse si l'incident concerne la SGP.", None),
    ("Dom", "E", "Identification", "Domaine", "Oui", "Liste",
     "Processus à l'origine de l'incident.", "Valorisation et VL"),
    ("Bale", "F", "Identification", "Catégorie d'événement (Bâle II)", "Recommandé", "Liste",
     "Classification des événements de risque opérationnel (Comité de Bâle, 2006) ; alimente la base historique des pertes.",
     "Exécution, livraison et gestion des processus"),
    ("Src", "G", "Identification", "Source de détection", "Oui", "Liste",
     "Qui a détecté l'incident ; l'indicateur Interne de l'onglet Données fixe la convention du taux de détection interne.",
     "Contrôle de 2nd niveau (Risk / Conformité)"),
    ("Presta", "H", "Identification", "Prestataire / tiers concerné", "Non", "Texte",
     "Délégataire ou tiers impliqué, le cas échéant.", "Administrateur de fonds"),
    ("Desc", "I", "Identification", "Description courte", "Oui", "Texte",
     "Une phrase factuelle.", "Écart de VL détecté au contrôle de cohérence"),
    ("Crit", "J", "Qualification", "Criticité", "Oui", "Liste",
     "Selon la matrice de l'onglet Données ; détermine les SLA et le niveau d'escalade requis.", "2 - Majeure"),
    ("DORA", "K", "Qualification", "Incident TIC majeur (DORA)", "Oui", "Liste Oui / Non",
     "Oui si l'incident est classé majeur selon le Règlement délégué (UE) 2024/1772.", "Non"),
    ("Statut", "L", "Qualification", "Statut", "Oui", "Liste",
     "Ouvert, En cours, En escalade, Résolu, Clos, Annulé ; une ligne Annulé est exclue des indicateurs.", "Clos"),
    ("Resp", "M", "Qualification", "Responsable", "Recommandé", "Texte",
     "Personne ou équipe en charge de la résolution.", "Middle-office"),
    ("Surv", "N", "Chronologie", "Date-heure de survenance", "Recommandé", "jj/mm/aaaa hh:mm",
     "Date de l'événement générateur (estimée si nécessaire).", "30/06/2026 18:00"),
    ("Det", "O", "Chronologie", "Date-heure de détection", "Oui", "jj/mm/aaaa hh:mm",
     "Prise de connaissance par la SGP ou son délégataire ; point de départ des délais d'escalade et DORA.",
     "15/07/2026 10:30"),
    ("Enr", "P", "Chronologie", "Date-heure d'enregistrement", "Oui", "jj/mm/aaaa hh:mm",
     "Inscription au registre ; rattache l'incident à une période.", "15/07/2026 11:00"),
    ("PEC", "Q", "Chronologie", "Date-heure de prise en compte", "Oui", "jj/mm/aaaa hh:mm",
     "Affectation d'un responsable et lancement des mesures conservatoires.", "15/07/2026 11:45"),
    ("Res", "R", "Chronologie", "Date-heure de résolution", "Si résolu", "jj/mm/aaaa hh:mm",
     "Impact contenu : VL corrigée, opération régularisée, service rétabli.", "17/07/2026 16:00"),
    ("Clo", "S", "Chronologie", "Date-heure de clôture", "Si clos", "jj/mm/aaaa hh:mm",
     "Clôture validée par le Risk Management après analyse de cause.", "31/07/2026 12:00"),
    ("EscN2", "T", "Escalade", "Date-heure escalade N2 (Contrôle)", "Si escaladé", "jj/mm/aaaa hh:mm",
     "Saisine formelle du Risk Management ou du RCCI pour décision.", "15/07/2026 12:00"),
    ("EscN3", "U", "Escalade", "Date-heure escalade N3 (Direction)", "Si escaladé", "jj/mm/aaaa hh:mm",
     "Information des dirigeants effectifs ou saisine du Comité des risques.", "Vide si non escaladé"),
    ("Reaf", "V", "Escalade", "Nombre de réaffectations", "Recommandé", "Nombre entier",
     "Nombre de changements d'équipe responsable (escalade fonctionnelle).", "1"),
    ("Reo", "W", "Qualité", "Réouvert", "Oui", "Liste Oui / Non",
     "Oui si l'incident a été rouvert après une première résolution.", "Non"),
    ("Lien", "X", "Qualité", "ID incident antérieur lié", "Si récurrent", "Texte",
     "ID d'un incident antérieur de même cause racine.", "INC-2026-003"),
    ("RCA", "Y", "Qualité", "Analyse de cause racine réalisée", "Oui pour criticités 1-2", "Liste Oui / Non",
     "Analyse documentée : cause, périmètre, correction.", "Oui"),
    ("NotReq", "Z", "Notifications", "Notification externe requise", "Oui", "Liste Oui / Non",
     "AMF, dépositaire, investisseurs ou CAC selon la réglementation, le règlement du fonds ou les conventions (hors DORA).",
     "Oui"),
    ("NotLim", "AA", "Notifications", "Date-heure limite de notification externe", "Si requise", "jj/mm/aaaa hh:mm",
     "Échéance issue de la procédure ou de la convention applicable.", "17/07/2026 18:00"),
    ("Not", "AB", "Notifications", "Date-heure de notification externe", "Si requise", "jj/mm/aaaa hh:mm",
     "Envoi effectif ; vaut escalade N4.", "16/07/2026 15:00"),
    ("DClas", "AC", "DORA", "Date-heure de classification majeur (DORA)", "Si DORA", "jj/mm/aaaa hh:mm",
     "Décision de classement en incident majeur lié aux TIC.", "02/09/2026 14:00"),
    ("DInit", "AD", "DORA", "Date-heure de notification initiale (DORA)", "Si DORA", "jj/mm/aaaa hh:mm",
     "Envoi à l'AMF ; vaut escalade N4.", "02/09/2026 16:30"),
    ("DInter", "AE", "DORA", "Date-heure du rapport intermédiaire (DORA)", "Si DORA", "jj/mm/aaaa hh:mm",
     "Dernier rapport intermédiaire transmis.", "05/09/2026 11:00"),
    ("DFin", "AF", "DORA", "Date du rapport final (DORA)", "Si DORA", "jj/mm/aaaa",
     "Rapport final transmis.", "29/09/2026"),
    ("PB", "AG", "Impact", "Perte brute estimée (EUR)", "Si impact", "Nombre",
     "Coût total : correction, indemnisation des investisseurs, frais.", "12 500"),
    ("Recup", "AH", "Impact", "Récupérations (EUR)", "Si impact", "Nombre",
     "Montants recouvrés : délégataire, assurance, contrepartie.", "12 500"),
    ("ActReq", "AI", "Actions", "Action corrective requise", "Oui", "Liste Oui / Non",
     "Oui si un plan d'action est ouvert.", "Oui"),
    ("Ech", "AJ", "Actions", "Échéance de l'action corrective", "Si action", "jj/mm/aaaa",
     "Date cible validée par le Risk Management.", "30/09/2026"),
    ("Real", "AK", "Actions", "Date de réalisation de l'action corrective", "Si réalisée", "jj/mm/aaaa",
     "Date de réalisation constatée.", "25/09/2026"),
    ("Com", "AL", "Actions", "Commentaire", "Non", "Texte", "Information complémentaire.", "-"),
]

# Champs calculés : clé, colonne, libellé, définition
CALCULS = [
    ("Ctrl", "AN", "Contrôle de saisie", "OK ou première anomalie détectée (champ obligatoire, chronologie, statut)."),
    ("Cpt", "AO", "Incident compté", "1 si Type = Incident et Statut différent de Annulé."),
    ("QI", "AP", "Quasi-incident compté", "1 si Type = Quasi-incident et Statut différent de Annulé."),
    ("Actif", "AQ", "Ligne active", "Incident ou quasi-incident non annulé."),
    ("CritN", "AR", "Criticité (numéro)", "1 à 4."),
    ("Int", "AS", "Détection interne", "1 si la source de détection est marquée Interne dans Données."),
    ("jDet", "AT", "Délai de détection (j.o.)", "Survenance à détection, en jours ouvrés."),
    ("hDecl", "AU", "Délai de déclaration (h)", "Détection à enregistrement, en heures ouvrées."),
    ("hPEC", "AV", "Délai de prise en compte (h)", "Enregistrement à prise en compte, en heures ouvrées."),
    ("jRes", "AW", "Délai de résolution (j.o.)", "Enregistrement à résolution, en jours ouvrés."),
    ("jClo", "AX", "Délai de clôture (j.o.)", "Enregistrement à clôture, en jours ouvrés."),
    ("cPEC", "AY", "Cible de prise en compte (h)", "Lue dans la matrice SLA selon la criticité."),
    ("okPEC", "AZ", "Prise en compte dans le SLA", "1 si délai de prise en compte inférieur ou égal à la cible."),
    ("cRes", "BA", "Cible de résolution (j.o.)", "Lue dans la matrice SLA selon la criticité."),
    ("okRes", "BB", "Résolution dans le SLA", "1 si délai de résolution inférieur ou égal à la cible."),
    ("DL", "BC", "Échéance SLA de résolution", "Enregistrement + cible en jours ouvrés (approximation à la journée)."),
    ("Niv", "BD", "Niveau maximal atteint", "4 si notification externe ou DORA, 3 si escalade N3, 2 si escalade N2, sinon 1."),
    ("NivM", "BE", "Niveau requis (matrice)", "Lu dans la matrice selon la criticité."),
    ("NivR", "BF", "Niveau requis (total)", "Matrice, porté à N4 si notification externe requise ou incident DORA."),
    ("EscOK", "BG", "Escalade conforme", "1 si niveau maximal atteint supérieur ou égal au niveau requis."),
    ("DEsc", "BH", "Date d'atteinte du niveau requis", "Première escalade au niveau requis par la matrice (N2 ou N3)."),
    ("hEsc", "BI", "Délai d'escalade (h)", "Détection à atteinte du niveau requis, en heures ouvrées."),
    ("EscDel", "BJ", "Escalade dans les délais", "1 si délai d'escalade inférieur ou égal au délai maximal de la matrice."),
    ("D1Esc", "BK", "Date de première escalade", "Première date entre escalade N2 et N3."),
    ("jEsc", "BL", "Temps en escalade (j.o.)", "Première escalade à résolution, en jours ouvrés."),
    ("ResN1", "BM", "Résolu au 1er niveau", "1 si résolu sans escalade (niveau maximal N1)."),
    ("ReoN", "BN", "Réouvert (1/0)", "1 si Réouvert = Oui."),
    ("Rec", "BO", "Récurrent (1/0)", "1 si un incident antérieur lié est renseigné."),
    ("RCAN", "BP", "Cause racine (1/0)", "1 si analyse de cause racine réalisée."),
    ("NotOK", "BQ", "Notification externe dans les délais", "1 si envoyée avant la limite, 0 si en retard ou non envoyée après la limite."),
    ("DoraDL", "BR", "DORA - échéance de notification initiale", "4 h après classification et au plus 24 h après détection ; 4 h après classification si celle-ci intervient après 24 h."),
    ("DoraI", "BS", "DORA - notification initiale", "1 si dans les délais, 0 sinon (y compris non envoyée après échéance)."),
    ("DoraM", "BT", "DORA - rapport intermédiaire", "1 si au plus 72 h après la notification initiale."),
    ("DoraF", "BU", "DORA - rapport final", "1 si au plus 1 mois après le rapport intermédiaire."),
    ("DoraOK", "BV", "DORA - conformité", "Minimum des trois contrôles évaluables."),
    ("PN", "BW", "Perte nette (EUR)", "Perte brute - récupérations."),
    ("ActOK", "BX", "Action corrective à échéance", "1 si réalisée au plus tard à l'échéance, 0 si en retard ou non réalisée après l'échéance."),
]

CATEGORIES = [
    ("V", "1. Volume et répartition"),
    ("D", "2. Délais et réactivité"),
    ("E", "3. Efficacité de résolution"),
    ("X", "4. Analyse des escalades"),
]

FREQ_M = "Mensuelle"
FREQ_T = "Trimestrielle"

# Dictionnaire des indicateurs.
# sens : "≥", "≤" ou "Suivi" ; base : contrôle de la base minimale (n) avant de juger le ratio.
KPIS = [
    # ---------------- 1. Volume et répartition
    dict(ref="V01", lib="Nombre d'incidents déclarés", unit="nb", sens="Suivi", cible=None, alerte=None, base="Non",
         src="Pas de cible : tendance",
         formule="N = nombre d'incidents (Type = Incident, Statut ≠ Annulé) dont la date-heure d'enregistrement est comprise dans [Début ; Fin].",
         excel='NB.SI.ENS(R_Cpt;1;R_Enr;">="&Début;R_Enr;"<"&Fin+1)',
         objectif="Mesurer l'exposition au risque opérationnel et la charge de traitement ; dénominateur des ratios ; alimente la base historique des pertes exigée par le Règlement délégué (UE) n° 231/2013, art. 13.",
         origine="Pas de cible absolue : une baisse peut traduire une sous-déclaration. Lecture en tendance (période précédente, 12 mois glissants).",
         champs=["ID", "Type", "Statut", "Enr"], freq=FREQ_M,
         vigilance="À lire avec V02 et V05 : un volume faible n'est pas un signal positif en soi."),
    dict(ref="V02", lib="Ratio quasi-incidents / incidents", unit="x", sens="≥", cible=1.0, alerte=0.5, base="Oui",
         src="Hypothèse à confirmer",
         formule="Nombre de quasi-incidents enregistrés sur la période / N (V01).",
         excel='NB.SI.ENS(R_QI;1;R_Enr;...) / V01',
         objectif="Mesurer la culture de déclaration : les quasi-incidents sont des signaux faibles qui permettent de corriger avant perte.",
         origine="Bonne pratique de gestion du risque opérationnel (pyramide de Bird) ; pas de norme ITSM. Confiance faible, à calibrer sur l'historique.",
         champs=["Type", "Statut", "Enr"], freq=FREQ_T,
         vigilance="Un ratio très bas signale le plus souvent une sous-déclaration, pas une absence de risque."),
    dict(ref="V03", lib="Part des incidents critiques et majeurs", unit="%", sens="≤", cible=0.10, alerte=0.20, base="Oui",
         src="Benchmark ITSM transposé - à calibrer",
         formule="Nombre d'incidents de criticité 1 ou 2 / N.",
         excel='NB.SI.ENS(R_Cpt;1;R_CritN;"<=2";R_Enr;...) / V01',
         objectif="Mesurer la gravité du profil de risque ; une hausse signale une dégradation du dispositif ou une sous-déclaration des incidents mineurs.",
         origine="Ordre de grandeur ITSM : priorités 1-2 généralement inférieures à 10-15 % des tickets. Cible SGP à calibrer sur 12 mois d'historique.",
         champs=["Crit", "Type", "Statut", "Enr"], freq=FREQ_T,
         vigilance="Dépend de la qualité de la cotation : contrôler la cohérence avec la matrice de criticité."),
    dict(ref="V04", lib="Nombre d'incidents critiques", unit="nb", sens="≤", cible=0, alerte=0, base="Non",
         src="Appétence au risque - hypothèse",
         formule="Nombre d'incidents de criticité 1 sur la période.",
         excel='NB.SI.ENS(R_Cpt;1;R_CritN;1;R_Enr;...)',
         objectif="Suivre les événements susceptibles d'affecter les investisseurs, la VL ou la conformité ; déclencheur d'information des dirigeants et du Comité des risques.",
         origine="Appétence au risque interne : tout incident critique est hors cible et fait l'objet d'une revue dédiée.",
         champs=["Crit", "Type", "Statut", "Enr"], freq=FREQ_M,
         vigilance="Indicateur absolu : pas de contrôle de base minimale."),
    dict(ref="V05", lib="Taux de détection interne", unit="%", sens="≥", cible=0.80, alerte=0.60, base="Oui",
         src="Bonne pratique - à confirmer",
         formule="Incidents détectés par le dispositif interne (contrôles de 1er et 2nd niveau, alerte automatique, délégataire) / incidents dont la source est renseignée.",
         excel='NB.SI.ENS(R_Int;1;R_Enr;...) / NB.SI.ENS(R_Int;">=0";R_Enr;...)',
         objectif="Mesurer l'efficacité du contrôle permanent : un incident révélé par un investisseur, le dépositaire, le CAC ou l'AMF traduit une défaillance de contrôle.",
         origine="Bonne pratique de contrôle interne ; pas de standard publié. Confiance moyenne.",
         champs=["Src", "Type", "Statut", "Enr"], freq=FREQ_T,
         vigilance="Convention à valider : un incident remonté par un délégataire est classé interne par défaut (modifiable dans Données)."),
    dict(ref="V06", lib="Concentration : part du premier domaine", unit="%", sens="≤", cible=0.30, alerte=0.50, base="Oui",
         src="Hypothèse à confirmer",
         formule="max sur les domaines d (nombre d'incidents du domaine d) / N.",
         excel='MAX(répartition par domaine du Dashboard) / V01',
         objectif="Identifier un processus défaillant (valorisation, passif, appels de fonds, reporting) et orienter le plan de contrôle.",
         origine="Hypothèse : au-delà de 30 % sur 12 mois, un domaine concentre le risque.",
         champs=["Dom", "Type", "Statut", "Enr"], freq=FREQ_T,
         vigilance="Non significatif sur une petite base : lire la colonne 12 mois glissants."),
    dict(ref="V07", lib="Perte opérationnelle nette", unit="EUR", sens="≤", cible=None, alerte=None, base="Non",
         src="À calibrer - seuil d'appétence",
         formule="Somme (perte brute estimée - récupérations) des incidents enregistrés sur la période.",
         excel='SOMME.SI.ENS(R_PN;R_Cpt;1;R_Enr;...)',
         objectif="Alimenter la base historique des pertes (Règlement délégué (UE) n° 231/2013, art. 13) et la mettre en regard des fonds propres supplémentaires ou de l'assurance RC professionnelle (art. 12 à 15) et de l'appétence au risque.",
         origine="Aucun standard : cible à fixer par la Direction (seuil d'appétence), non renseignée par défaut.",
         champs=["PB", "Recup", "Type", "Statut", "Enr"], freq=FREQ_T,
         vigilance="Montants estimés à la déclaration : mettre à jour à la clôture (perte définitive)."),
    dict(ref="V08", lib="Nombre d'incidents TIC majeurs (DORA)", unit="nb", sens="≤", cible=0, alerte=0, base="Non",
         src="Appétence au risque - hypothèse",
         formule="Nombre d'incidents classés « incident majeur lié aux TIC » sur la période.",
         excel='NB.SI.ENS(R_Cpt;1;R_DORA;"Oui";R_Enr;...)',
         objectif="Suivre l'exposition au risque TIC et les obligations de notification à l'AMF (Règlement (UE) 2022/2554, art. 17 à 19).",
         origine="Appétence au risque interne.",
         champs=["DORA", "Type", "Statut", "Enr"], freq=FREQ_M,
         vigilance="Classification selon le Règlement délégué (UE) 2024/1772 ; documenter chaque décision de non-classement."),
    # ---------------- 2. Délais et réactivité
    dict(ref="D01", lib="Délai moyen de détection (MTTD)", unit="j.o.", sens="≤", cible=2, alerte=5, base="Oui",
         src="Hypothèse SGP non cotée",
         formule="Somme (détection - survenance) en jours ouvrés / nombre d'incidents dont les deux dates sont renseignées.",
         excel='MOYENNE.SI.ENS(R_jDet;R_Cpt;1;R_Enr;...)',
         objectif="Mesurer la latence des erreurs (VL, allocation d'un appel de fonds, ratio) : plus la détection est tardive, plus la correction est coûteuse (recalcul de VL, indemnisation).",
         origine="Pas de benchmark ITSM direct ; hypothèse cohérente avec un cycle de valorisation mensuel ou trimestriel.",
         champs=["Surv", "Det", "Enr"], freq=FREQ_T,
         vigilance="Moyenne tirée par les erreurs latentes de plusieurs mois : examiner les incidents au-delà de 20 j.o."),
    dict(ref="D02", lib="Délai moyen de déclaration", unit="h", sens="≤", cible=4, alerte=9, base="Oui",
         src="Pratique de place - à aligner sur la procédure",
         formule="Somme (enregistrement - détection) en heures ouvrées / nombre d'incidents.",
         excel='MOYENNE.SI.ENS(R_hDecl;R_Cpt;1;R_Enr;...)',
         objectif="Discipline de remontée au registre et aux fonctions de contrôle ; condition du respect des délais réglementaires (DORA : 24 h).",
         origine="Pratique de place : déclaration le jour même. Cible à aligner sur la procédure de gestion des incidents.",
         champs=["Det", "Enr"], freq=FREQ_M,
         vigilance="Les heures ouvrées n'intègrent pas les week-ends : les délais DORA, eux, courent en heures calendaires."),
    dict(ref="D03", lib="Temps moyen de prise en compte (MTTA)", unit="h", sens="≤", cible=4, alerte=9, base="Oui",
         src="Benchmark ITSM - à confirmer",
         formule="Somme (prise en compte - enregistrement) en heures ouvrées / nombre d'incidents pris en compte.",
         excel='MOYENNE.SI.ENS(R_hPEC;R_Cpt;1;R_Enr;...)',
         objectif="Réactivité de l'affectation d'un responsable et du lancement des mesures conservatoires.",
         origine="ITSM : réponse de 15 min (P1) à 8 h (P4). La cible par criticité figure dans la matrice SLA de Données.",
         champs=["Enr", "PEC"], freq=FREQ_M,
         vigilance="Moyenne toutes criticités : lire avec D04, qui tient compte de la cible propre à chaque criticité."),
    dict(ref="D04", lib="Respect du SLA de prise en compte", unit="%", sens="≥", cible=0.95, alerte=0.85, base="Oui",
         src="Standard ITSM",
         formule="Incidents pris en compte dans la cible SLA de leur criticité / incidents pris en compte.",
         excel='NB.SI.ENS(R_okPEC;1;R_Enr;...) / NB.SI.ENS(R_okPEC;">=0";R_Enr;...)',
         objectif="Vérifier que chaque incident est traité dans le délai attendu pour sa gravité.",
         origine="Standard ITSM : taux de respect des SLA de réponse supérieur ou égal à 95 %.",
         champs=["Crit", "Enr", "PEC"], freq=FREQ_M,
         vigilance="Sur une base inférieure à la base minimale, un seul dépassement fait varier le taux de plus de 20 points."),
    dict(ref="D05", lib="Temps moyen de résolution (MTTR)", unit="j.o.", sens="≤", cible=5, alerte=10, base="Oui",
         src="Hypothèse SGP non cotée",
         formule="Somme (résolution - enregistrement) en jours ouvrés / nombre d'incidents résolus sur la période.",
         excel='MOYENNE.SI.ENS(R_jRes;R_Res;">="&Début;R_Res;"<"&Fin+1)',
         objectif="Capacité à contenir l'impact (VL corrigée, opération régularisée, service rétabli) ; la résolution précède la clôture.",
         origine="ITSM : quelques heures pour un service desk IT, non transposable aux incidents de valorisation ou de passif ; cible SGP hypothétique.",
         champs=["Enr", "Res"], freq=FREQ_M,
         vigilance="Rattaché à la date de résolution ; lire avec D06 (90e centile) et le MTTR par criticité du Dashboard."),
    dict(ref="D06", lib="Délai de résolution - 90e centile", unit="j.o.", sens="≤", cible=10, alerte=20, base="Oui",
         src="Hypothèse SGP non cotée",
         formule="90e centile de la distribution (résolution - enregistrement) des incidents résolus sur la période.",
         excel='{=CENTILE(SI(ESTNUM(R_jRes)*(R_Res>=Début)*(R_Res<Fin+1);R_jRes);0,9)} (formule matricielle)',
         objectif="Mesurer la queue de distribution : les dossiers qui s'éternisent, invisibles dans la moyenne.",
         origine="Hypothèse alignée sur le SLA de résolution de la criticité 3.",
         champs=["Enr", "Res"], freq=FREQ_T,
         vigilance="Avec moins de 10 incidents résolus, le 90e centile est proche du maximum."),
    dict(ref="D07", lib="Respect du SLA de résolution", unit="%", sens="≥", cible=0.90, alerte=0.80, base="Oui",
         src="Standard ITSM",
         formule="Incidents résolus dans la cible SLA de leur criticité / incidents résolus sur la période.",
         excel='NB.SI.ENS(R_okRes;1;R_Res;...) / NB.SI.ENS(R_okRes;">=0";R_Res;...)',
         objectif="Indicateur de service principal : respect des engagements de résolution par niveau de gravité.",
         origine="Standard ITSM : 90 à 95 %.",
         champs=["Crit", "Enr", "Res"], freq=FREQ_M,
         vigilance="Ne voit pas les incidents non résolus en dépassement : lire avec E04."),
    dict(ref="D08", lib="Délai moyen de clôture", unit="j.o.", sens="≤", cible=20, alerte=40, base="Oui",
         src="Pratique de place - hypothèse",
         formule="Somme (clôture - enregistrement) en jours ouvrés / nombre d'incidents clos sur la période.",
         excel='MOYENNE.SI.ENS(R_jClo;R_Clo;">="&Début;R_Clo;"<"&Fin+1)',
         objectif="Délai complet incluant l'analyse de cause et la validation par les fonctions de contrôle ; un écart important avec le MTTR signale des dossiers résolus mais non soldés.",
         origine="Pratique de place : clôture sous un mois environ. Hypothèse.",
         champs=["Enr", "Clo"], freq=FREQ_T,
         vigilance="Dépend de la discipline de clôture formelle dans le registre."),
    # ---------------- 3. Efficacité de résolution
    dict(ref="E01", lib="Résolution au 1er niveau (criticités 3 et 4)", unit="%", sens="≥", cible=0.80, alerte=0.65, base="Oui",
         src="Benchmark ITSM adapté",
         formule="Incidents de criticité 3-4 résolus sans escalade (niveau maximal N1) / incidents de criticité 3-4 résolus.",
         excel='NB.SI.ENS(R_ResN1;1;R_CritN;">=3";R_Res;...) / NB.SI.ENS(R_ResN1;">=0";R_CritN;">=3";R_Res;...)',
         objectif="Transposition du « First Contact Resolution » ITIL : autonomie des équipes et des délégataires sur les incidents courants.",
         origine="Benchmark service desk : FCR de l'ordre de 70-75 % ; cible relevée car le périmètre exclut les criticités 1-2, dont l'escalade est obligatoire.",
         champs=["Crit", "Res", "EscN2", "EscN3", "Not", "DInit"], freq=FREQ_T,
         vigilance="Un taux élevé n'est sain que si X04 (conformité de l'escalade) est à 100 %."),
    dict(ref="E02", lib="Ratio de traitement (résolus / nouveaux)", unit="x", sens="≥", cible=1.0, alerte=0.8, base="Oui",
         src="Standard ITSM",
         formule="Nombre d'incidents résolus sur la période / N.",
         excel='NB.SI.ENS(R_Cpt;1;R_Res;...) / V01',
         objectif="Capacité d'absorption : un ratio inférieur à 1 signifie que le stock d'incidents ouverts augmente.",
         origine="Standard ITSM (closure ratio).",
         champs=["Enr", "Res"], freq=FREQ_M,
         vigilance="Volatil sur une période courte : privilégier la lecture 12 mois."),
    dict(ref="E03", lib="Backlog en fin de période", unit="nb", sens="Suivi", cible=None, alerte=None, base="Non",
         src="Pas de cible : tendance",
         formule="Incidents enregistrés avant la fin de période et non résolus à cette date.",
         excel='NB.SI.ENS(R_Cpt;1;R_Enr;"<"&Fin+1) - NB.SI.ENS(R_Cpt;1;R_Enr;"<"&Fin+1;R_Res;"<"&Fin+1)',
         objectif="Stock de risque non maîtrisé à la date d'arrêté, à présenter au Comité des risques.",
         origine="Pas de cible absolue : comparer au flux mensuel (backlog inférieur à un mois de flux entrant).",
         champs=["Enr", "Res"], freq=FREQ_M,
         vigilance="Calculé en date de résolution : un incident résolu mais non clos sort du backlog."),
    dict(ref="E04", lib="Part du backlog hors SLA", unit="%", sens="≤", cible=0.10, alerte=0.25, base="Oui",
         src="Standard ITSM",
         formule="Incidents du backlog dont l'échéance SLA de résolution est dépassée en fin de période / backlog (E03).",
         excel='[NB.SI.ENS(R_Cpt;1;R_Enr;"<"&Fin+1;R_DL;"<"&Fin+1) - idem résolus avant Fin+1] / E03',
         objectif="Mesurer le vieillissement du stock : dossiers ouverts au-delà du délai attendu.",
         origine="Standard ITSM (aged backlog) ; cible usuelle inférieure à 10 %.",
         champs=["Crit", "Enr", "Res"], freq=FREQ_M,
         vigilance="Échéance calculée en jours ouvrés depuis l'enregistrement (approximation à la journée)."),
    dict(ref="E05", lib="Taux de réouverture", unit="%", sens="≤", cible=0.05, alerte=0.10, base="Oui",
         src="Standard ITSM",
         formule="Incidents réouverts / incidents résolus sur la période.",
         excel='NB.SI.ENS(R_ReoN;1;R_Res;...) / NB.SI.ENS(R_Cpt;1;R_Res;...)',
         objectif="Qualité de la résolution : correction incomplète ou mauvais diagnostic.",
         origine="Standard ITSM : inférieur à 5 %.",
         champs=["Reo", "Res"], freq=FREQ_T,
         vigilance="Suppose que l'incident est rouvert sur la même ligne (et non recréé)."),
    dict(ref="E06", lib="Taux de récurrence", unit="%", sens="≤", cible=0.10, alerte=0.20, base="Oui",
         src="Bonne pratique ITIL - hypothèse",
         formule="Incidents rattachés à un incident antérieur de même cause / N.",
         excel='NB.SI.ENS(R_Rec;1;R_Enr;...) / V01',
         objectif="Efficacité de la gestion des problèmes (ITIL Problem Management) : un incident récurrent révèle une action corrective inefficace.",
         origine="Bonne pratique ITIL ; cible hypothétique.",
         champs=["Lien", "Enr"], freq=FREQ_T,
         vigilance="Dépend de la rigueur du rattachement par le déclarant ; revue par le Risk Management recommandée."),
    dict(ref="E07", lib="Couverture des analyses de cause racine (criticités 1 et 2)", unit="%", sens="≥", cible=1.0, alerte=0.90, base="Non",
         src="Bonne pratique - exigence interne",
         formule="Incidents de criticité 1-2 clos avec analyse de cause racine / incidents de criticité 1-2 clos sur la période.",
         excel='NB.SI.ENS(R_RCAN;1;R_CritN;"<=2";R_Clo;...) / NB.SI.ENS(R_Cpt;1;R_CritN;"<=2";R_Clo;...)',
         objectif="Garantir que chaque incident grave donne lieu à une analyse documentée avant clôture.",
         origine="Bonne pratique ITIL et attente usuelle de contrôle interne : 100 %.",
         champs=["Crit", "RCA", "Clo"], freq=FREQ_T,
         vigilance="Indicateur de conformité : jugé quel que soit n."),
    dict(ref="E08", lib="Actions correctives réalisées à échéance", unit="%", sens="≥", cible=0.90, alerte=0.75, base="Oui",
         src="Pratique de place - hypothèse",
         formule="Actions réalisées au plus tard à l'échéance / actions dont l'échéance tombe dans la période (réalisées ou non).",
         excel='NB.SI.ENS(R_ActOK;1;R_Ech;...) / NB.SI.ENS(R_ActOK;">=0";R_Ech;...)',
         objectif="Suivi du plan d'action, point d'attention récurrent du RCCI et des contrôles AMF.",
         origine="Pratique de place ; cible hypothétique.",
         champs=["ActReq", "Ech", "Real"], freq=FREQ_T,
         vigilance="Inclut les actions issues de quasi-incidents ; une action non réalisée après échéance compte en échec."),
    # ---------------- 4. Analyse des escalades
    dict(ref="X01", lib="Taux d'escalade global (N2 et plus)", unit="%", sens="≤", cible=0.30, alerte=0.40, base="Oui",
         src="Benchmark ITSM - hypothèse",
         formule="Incidents ayant atteint au moins le niveau N2 / N.",
         excel='NB.SI.ENS(R_Niv;">=2";R_Enr;...) / V01',
         objectif="Mesurer la dépendance aux fonctions de contrôle et à la Direction : un taux élevé révèle un manque d'autonomie du 1er niveau.",
         origine="Benchmark service desk : escalade du niveau 1 vers le niveau 2 de l'ordre de 20-30 %. Hypothèse.",
         champs=["EscN2", "EscN3", "Not", "DInit", "Enr"], freq=FREQ_T,
         vigilance="Un taux bas n'est rassurant que si X04 est à 100 % (pas de sous-escalade)."),
    dict(ref="X02", lib="Taux d'escalade à la Direction (N3 et plus)", unit="%", sens="≤", cible=0.10, alerte=0.20, base="Oui",
         src="Hypothèse - cohérence avec V03",
         formule="Incidents ayant atteint N3 (dirigeants effectifs, Comité des risques) ou N4 / N.",
         excel='NB.SI.ENS(R_Niv;">=3";R_Enr;...) / V01',
         objectif="Mesurer la charge de décision remontée à la Direction.",
         origine="Cohérence avec la part des incidents critiques et majeurs (V03).",
         champs=["EscN3", "Not", "DInit", "Enr"], freq=FREQ_T,
         vigilance="Le détail N1 à N4 figure dans la répartition par niveau du Dashboard."),
    dict(ref="X03", lib="Taux d'escalade externe (N4)", unit="%", sens="Suivi", cible=None, alerte=None, base="Non",
         src="Pas de cible : obligation",
         formule="Incidents ayant donné lieu à une notification externe (AMF, dépositaire, investisseurs, CAC) / N.",
         excel='NB.SI.ENS(R_Niv;4;R_Enr;...) / V01',
         objectif="Mesurer l'exposition réglementaire et réputationnelle.",
         origine="Pas de cible de performance : la notification découle d'une obligation.",
         champs=["Not", "DInit", "Enr"], freq=FREQ_T,
         vigilance="La qualité des notifications se lit dans X09 et X10."),
    dict(ref="X04", lib="Conformité à la matrice d'escalade", unit="%", sens="≥", cible=1.0, alerte=0.95, base="Non",
         src="Exigence interne de gouvernance",
         formule="Incidents dont le niveau maximal atteint est supérieur ou égal au niveau requis (matrice selon criticité ; N4 si notification requise ou DORA) / incidents.",
         excel='NB.SI.ENS(R_EscOK;1;R_Enr;...) / NB.SI.ENS(R_EscOK;">=0";R_Enr;...)',
         objectif="Détecter la sous-escalade, principal risque de gouvernance : dirigeants non informés d'un incident critique.",
         origine="Exigence interne : 100 %.",
         champs=["Crit", "DORA", "NotReq", "EscN2", "EscN3", "Not", "DInit", "Enr"], freq=FREQ_M,
         vigilance="Indicateur de conformité : jugé quel que soit n."),
    dict(ref="X05", lib="Escalades réalisées dans les délais", unit="%", sens="≥", cible=0.95, alerte=0.85, base="Oui",
         src="Exigence interne - hypothèse",
         formule="Incidents escaladés au niveau requis dans le délai maximal de la matrice, compté depuis la détection / incidents escaladés au niveau requis (N2 ou N3).",
         excel='NB.SI.ENS(R_EscDel;1;R_Enr;...) / NB.SI.ENS(R_EscDel;">=0";R_Enr;...)',
         objectif="Vérifier que l'information parvient au bon niveau à temps pour décider.",
         origine="Exigence interne ; délais de la matrice à valider en Comité des risques.",
         champs=["Crit", "Det", "EscN2", "EscN3", "Enr"], freq=FREQ_M,
         vigilance="Les incidents non escaladés alors qu'ils devaient l'être sont captés par X04, pas par X05."),
    dict(ref="X06", lib="Délai moyen d'escalade au niveau requis", unit="h", sens="≤", cible=2, alerte=4, base="Oui",
         src="Exigence interne - hypothèse",
         formule="Somme (atteinte du niveau requis par la matrice - détection) en heures ouvrées / incidents escaladés au niveau requis (N2 ou N3).",
         excel='MOYENNE.SI.ENS(R_hEsc;R_Cpt;1;R_Enr;...)',
         objectif="Mesurer la vitesse de remontée de l'information vers le niveau de décision ; complète X05 en donnant l'ampleur des retards.",
         origine="Hypothèse cohérente avec les délais maximaux de la matrice (2 h pour la criticité 1, 4 h pour la criticité 2).",
         champs=["Crit", "Det", "EscN2", "EscN3", "Enr"], freq=FREQ_M,
         vigilance="Porte sur les seuls incidents dont la matrice exige une escalade (criticités 1 et 2 par défaut)."),
    dict(ref="X07", lib="Temps moyen passé en escalade", unit="j.o.", sens="≤", cible=3, alerte=5, base="Oui",
         src="Hypothèse",
         formule="Somme (résolution - première escalade N2 ou N3) en jours ouvrés / incidents escaladés résolus sur la période.",
         excel='MOYENNE.SI.ENS(R_jEsc;R_Res;">="&Début;R_Res;"<"&Fin+1)',
         objectif="Mesurer le délai de décision et de traitement une fois l'incident remonté aux fonctions de contrôle ou à la Direction.",
         origine="Hypothèse ; pas de standard de marché.",
         champs=["EscN2", "EscN3", "Res"], freq=FREQ_T,
         vigilance="Inclut le temps d'exécution après décision ; dans une SGP, les criticités 1-2 sont escaladées dès la détection, "
                   "ce délai est donc proche du MTTR de ces incidents."),
    dict(ref="X08", lib="Taux de réaffectation multiple", unit="%", sens="≤", cible=0.10, alerte=0.20, base="Oui",
         src="Standard ITSM",
         formule="Incidents réaffectés au moins 2 fois / incidents dont le nombre de réaffectations est renseigné.",
         excel='NB.SI.ENS(R_Cpt;1;R_Reaf;">=2";R_Enr;...) / NB.SI.ENS(R_Cpt;1;R_Reaf;">=0";R_Enr;...)',
         objectif="Escalade fonctionnelle mal orientée (« ping-pong » entre SGP, administrateur, dépositaire, agent de transfert) : signe d'un RACI incomplet dans les conventions de délégation.",
         origine="Standard ITSM (hop rate, reassignment rate).",
         champs=["Reaf", "Enr"], freq=FREQ_T,
         vigilance="Exige la saisie systématique du nombre de réaffectations (0 compris)."),
    dict(ref="X09", lib="Notifications externes dans les délais", unit="%", sens="≥", cible=1.0, alerte=1.0, base="Non",
         src="Obligation réglementaire ou contractuelle",
         formule="Notifications externes (AMF, dépositaire, investisseurs, CAC) envoyées au plus tard à la date limite / notifications requises échues.",
         excel='NB.SI.ENS(R_NotOK;1;R_Enr;...) / NB.SI.ENS(R_NotOK;">=0";R_Enr;...)',
         objectif="Conformité réglementaire et contractuelle (règlement ou prospectus du fonds, convention dépositaire).",
         origine="Obligation : 100 %.",
         champs=["NotReq", "NotLim", "Not", "Enr"], freq=FREQ_M,
         vigilance="Une notification non envoyée après la limite compte en échec à la date de calcul (fonction MAINTENANT)."),
    dict(ref="X10", lib="Conformité des notifications DORA", unit="%", sens="≥", cible=1.0, alerte=1.0, base="Non",
         src="Règlement (UE) 2022/2554 et RD (UE) 2025/301",
         formule="Incidents TIC majeurs dont la notification initiale (4 h après classification, 24 h au plus après détection), le rapport intermédiaire (72 h) et le rapport final (1 mois) respectent les délais / incidents TIC majeurs évaluables.",
         excel='NB.SI.ENS(R_DoraOK;1;R_Enr;...) / NB.SI.ENS(R_DoraOK;">=0";R_Enr;...)',
         objectif="Conformité aux obligations de notification des incidents majeurs liés aux TIC à l'AMF.",
         origine="Réglementaire : Règlement (UE) 2022/2554, art. 19 ; Règlement délégué (UE) 2025/301 (délais). 100 %.",
         champs=["DORA", "Det", "DClas", "DInit", "DInter", "DFin", "Enr"], freq=FREQ_M,
         vigilance="Délais en heures calendaires ; assouplissements éventuels week-end et jours fériés non modélisés (à vérifier)."),
]
